### ISSUE TITLE
seg fault (gcc-7 -O3) when copying shared mem to local mem in for loop

### ISSUE THREAD

**Issue by oguyon** [milk-org/COREMOD_memory#2]
Encountering a seg fault in sample code below when compiling with gcc-7 -O3 or -Ofast.
This doesn't affect gcc-6
crash only occurs when doing element-by-element copy in a for loop. memcpy is OK
crash only occurs when copying from shared memory array. Copy from local memory is OK.

... any idea what could be happening ?

```C
/**
 * 
 * Test function aimed at creating unsolved seg fault bug
 * Will crash under gcc-7 if -O3 or -Ofast gcc compilation flag
 * 
 */
int_fast8_t COREMOD_MEMORY_testfunc()
{
	long ID;
	long IDimc;
	uint32_t xsize, ysize, xysize;
	uint32_t ii;
	uint32_t *imsize;
	IMAGE testimage_in;
	IMAGE testimage_out;
	
	
	
	printf("Entering test function\n");
	fflush(stdout);
	
	xsize = 50;
	ysize = 50;
	imsize = (uint32_t*) malloc(sizeof(uint32_t)*2);
	imsize[0] = xsize;
	imsize[1] = ysize;
	xysize = xsize*ysize;
	
	// create image (shared memory)   
	ImageStreamIO_createIm(&testimage_in, "testimshm", 2, imsize, _DATATYPE_UINT32, 1, 0);
	
	// create image (local memory only)
	ImageStreamIO_createIm(&testimage_out, "testimout", 2, imsize, _DATATYPE_UINT32, 0, 0);


	// crashes with seg fault with gcc-7.3.0 -O3
	// tested with float (.F) -> crashes
	// tested with uint32 (.UI32) -> crashes
	// no crash with gcc-6.3.0 -O3
	// crashes with gcc-7.2.0 -O3
	for(ii=0; ii<xysize; ii++){
		testimage_out.array.UI32[ii] = testimage_in.array.UI32[ii];
	}

	// no seg fault with gcc-7.3.0 -O3
	//memcpy(testimage_out.array.UI32, testimage_in.array.UI32, SIZEOF_DATATYPE_UINT32*xysize);


	free(imsize);

	printf("No bug... clean exit\n");
	fflush(stdout);
	
	return(0);
}
```

**Comment by oguyon** [comment]
For easy testing, this function is now in COREMOD_memory, called from CLI:
> cmemtestf

**Comment by a-sevin** [comment]
I have also a strange comportment with 7.3 with ImageIOStream, this is why I changed the ImageIOStream code

**Comment by a-sevin** [comment]
```C
	for(ii=0; ii<xysize; ii++){
		testimage_out.array.UI32[ii] = testimage_in.array.UI32[ii];
	}
```

that works on gcc 7.3.1 -O2 but not with -O3...

**Comment by a-sevin** [comment]
adding printf "solved" the issue...

```C
	for(ii=0; ii<xysize; ++ii){
        printf("ii: %d\r", ii);
		testimage_out.array.UI32[ii] = testimage_in.array.UI32[ii];
	}
```

A possible explanation from Julien, the "printf" brokes the vectorization optimization of GCC and it does element by element...

Maybe the array is not well aligned?

**Comment by a-sevin** [comment]
```C
	for(ii=0; ii<8; ii++){
		testimage_out.array.UI32[ii] = testimage_in.array.UI32[ii];
	}
```
Works...
```C
	for(ii=0; ii<9; ii++){
		testimage_out.array.UI32[ii] = testimage_in.array.UI32[ii];
	}
```
Segmentation fault (core dumped)
Maybe something around AV256 ?

**Comment by oguyon** [comment]
... I did see the same thing... printf removes the error.
I produced the error on 2 different computers (both Ubuntu)

**Comment by oguyon** [comment]
Will test without data packing ... maybe I was indeed playing with fire with the memory packing. 
As Julien suggests, it's quite likely the array is not well aligned with the packed structure

**Comment by a-sevin** [comment]
I try to compile cacao with clang without success...

**Comment by oguyon** [comment]
I tested WITHOUT data packing: the error does not occur.
This does indeed suggest a memory alignment issue - Thanks to Julien & Arnaud for putting us on the right path 
I
 updated dev and master branches accordingly... not more __packed__

Since we are no longer using __packed__, I am closing this issue.
